.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH INFON 6 "November 21, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
infon \- Program bugs to compete for food and survival
.SH SYNOPSIS

infon [\fB\-r\fR <renderer>] [\fB\-f\fR] [\fB\-x\fR <width>] [\fB\-y\fR <height>] [\fB\-v\fR] [\fB\-h\fR] <server[:port]>

.SH DESCRIPTION
\fBinfonx\fP is the graphical viewers for the infon game.
Infon is a game which simulates the live of simple bugs who eat,
propagate, eat each other and evolve. The players can not control
the bugs directly but write their "intelligence" in the simple
script language lua and upload it to the game using a plain telnet
connection. The code can then be modified even while the game
is running.

You have to specify the hostname of the server to connect to on the 
command line.

.SH OPTIONS
.HP
\fB\-r\fR <renderer>    \- renderer to use (sdl_gui, gl_gui, ...)
.HP
\fB\-x\fR <width>       \- initial screen width.
.HP
\fB\-y\fR <height>      \- initial screen height.
.HP
\fB\-f\fR               \- start in fullscreen mode.
.HP
\fB\-v\fR               \- display version information.
.HP
\fB\-h\fR               \- this help.
.PP
<server[:port]>   \- ip/hostname of an infon game server.
if not port is given, 1234 is used.

.SH SEE ALSO
.BR infond (8)

.SH AUTHOR
infon was written by Florian Wesch <fw@dividuum.de>
.PP
This manual page was written by Joachim Breitner <nomeata@debian.org>,
for the Debian project (but may be used by others).
