.TH INFON-DEVEL "1" "November 2006" "infon-devel" "User Commands"
.SH NAME
infon-devel \- write bots for the game infon
.SH DESCRIPTION
Infon is a game which simulates the live of simple bugs who eat,
propagate, eat each other and evolve. The players can not control
the bugs directly but write their "intelligence" in the simple
script language lua and upload it to the game using a plain telnet
connection. The code can then be modified even while the game
is running.

Infon Devel is a graphical lua editor with integration into
the infon server and allows easy uploading of the code. It also
marks the currently executed line of code.

.SH SEE ALSO
.BR infon (6)
.BR infond (6)
